### ISSUE TITLE
Err on opening folder /etc

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_project_man#45]
Ubuntu 16.4
File/Open, folder /etc
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_project_man/__init__.py", line 733, in tree_on_unfold
    self.action_refresh(data, sub_nodes)
  File "/home/user/.cudatext/py/cuda_project_man/__init__.py", line 418, in action_refresh
    sub_nodes = sorted(path.iterdir(), key=Command.node_ordering)
  File "/home/user/.cudatext/py/cuda_project_man/pathlib.py", line 982, in iterdir
    for name in self._accessor.listdir(self):
  File "/home/user/.cudatext/py/cuda_project_man/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/etc/docker'
```

**Comment by pohmelie** [comment]
What is permissions for `/etc/docker`?

**Comment by Alexey-T** [comment]
don't know:
```
user@user-Notebook:~$ ls /etc/doc*
/etc/doc-base:
documents
ls: cannot open directory '/etc/docker': Permission denied
```

**Comment by pohmelie** [comment]
You can use `sudo ls -la /etc/doc*`

**Comment by Alexey-T** [comment]
drwx------  2 root root     4096 сен  9  2016 docker

**Comment by pohmelie** [comment]
You have no permissions to read `/etc/docker`, that is why plugin failed.

**Comment by Alexey-T** [comment]
Can we handle exception and not show er in console?

**Comment by pohmelie** [comment]
And what to do in case of exception?

**Comment by Alexey-T** [comment]
Show item as empty file. better set NODE_BAD to it.
