### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#52]
Открываю Куд. 
Открываю файл проекта (через Ctrl+O).
Вызываю `ed.cmd(cmds.cmd_ResetPythonPlugins)`, чтобы тестировать свой плагин.
Из панели Проект вызываю `Open project` и выбираю тот же файл.
Вижу сбой:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Programs\CudaText\py\cuda_project_man\__init__.py", line 497, in action_open_project
    self.add_recent(path)
  File "C:\Programs\CudaText\py\cuda_project_man\__init__.py", line 314, in add_recent
    self.generate_context_menu()
  File "C:\Programs\CudaText\py\cuda_project_man\__init__.py", line 236, in generate_context_menu
    if self.selected is not None:
  File "C:\Programs\CudaText\py\cuda_project_man\__init__.py", line 228, in selected
    return tree_proc(self.tree, TREE_ITEM_GET_SELECTED)
  File "C:\Programs\CudaText\py\cudatext.py", line 816, in tree_proc
    return ct.tree_proc(id_tree, id_action, id_item, index, to_str(text), image_index)
TypeError: an integer is required (got type NoneType)
```

**Comment by Alexey-T** [comment]
плагин может не поддерживать ResetPythonPlugins commd.
