### ISSUE TITLE
(bug) Recents

### ISSUE THREAD

**Issue by kvichans** [pohmelie/cuda_project_man#7]
Try to switch to prev proj with local menu
![pj-recent1](https://cloud.githubusercontent.com/assets/7419630/16908534/1d7dc108-4cd5-11e6-8555-94762daa9555.PNG)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Programs\CudaText\py\cuda_project_man\__init__.py", line 234, in action_open_project
    with open(path) as fin:
OSError: [Errno 22] Invalid argument: 'C:\\Programs\\CudaText\tmp\t.cuda-proj'
```

**Comment by Alexey-T** [comment]
try this-

~~~
      "cuda_project_man,action_open_project,'{}'",
~~~
here `'{}'` to `r'{}'`

**Comment by kvichans** [comment]
What/where?

**Comment by Alexey-T** [comment]
in `__init__.py` find this line.

**Comment by Alexey-T** [comment]
Fixed?

**Comment by kvichans** [comment]
стало лучше
